# Site settings
title: Davin Kelly
description: "Designer // Developer // Worker"
email: email@email.com

# Build settings
markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  # style: :compressed
  style: nested